name: Crypto Scanner Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: pip install ccxt pandas numpy requests
    - run: python main.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
